import gregtech.api.GTValues;


recipemap('assembler').recipeBuilder()
        .inputs(ore('plateElite') * 16)
        .inputs(ore('screwExtreme') * 8)
        .inputs(ore('plateThermoconducting') * 4)
        .inputs(ore('circuitEv') * 4)
        .inputs(ore('processorBasic') * 2)
        .inputs(item('qmd:accelerator_casing'))
        .fluidInputs(fluid('saturnite') * 1296)
        .outputs(item('qmd:linear_accelerator_controller'))
        .duration(420).EUt(GTValues.VA[GTValues.HV]).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateElite') * 64)
        .inputs(ore('screwExtreme') * 32)
        .inputs(ore('plateThermoconducting') * 16)
        .inputs(ore('processorAdvanced') * 16)
        .inputs(ore('circuitIv') * 8)
        .inputs(item('qmd:accelerator_casing'))
        .fluidInputs(fluid('saturnite') * 4096)
        .outputs(item('qmd:ring_accelerator_controller'))
        .duration(420).EUt(GTValues.VA[GTValues.HV]).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateElite') * 16)
        .inputs(ore('plateTungCar') * 12)
        .inputs(ore('plateThermoconducting') * 8)
        .inputs(ore('screwExtreme') * 4)
        .inputs(ore('processorBasic') * 2)
        .fluidInputs(fluid('saturnite') * 1296)
        .outputs(item('qmd:accelerator_casing') * 4)
        .duration(120).EUt(GTValues.VA[GTValues.HV]).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateElite') * 16)
        .inputs(ore('wireFineTungstenSteel') * 32)
        .inputs(ore('wireFineGold') * 32)
        .inputs(ore('plateTungstenSteel') * 8)
        .inputs(ore('screwExtreme') * 4)
        .inputs(ore('processorBasic') * 2)
        .fluidInputs(fluid('tungsten_steel') * 1296)
        .outputs(item('qmd:particle_chamber_casing') * 4)
        .duration(120).EUt(GTValues.VA[GTValues.HV]).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateElite') * 16)
        .inputs(ore('wireFineTungstenSteel') * 32)
        .inputs(ore('wireFineGold') * 32)
        .inputs(ore('plateTungstenSteel') * 8)
        .inputs(ore('screwExtreme') * 4)
        .inputs(ore('processorBasic') * 2)
        .fluidInputs(fluid('tungsten_steel') * 1296)
        .outputs(item('qmd:particle_chamber_casing') * 4)
        .duration(120).EUt(GTValues.VA[GTValues.HV]).buildAndRegister()

// target chamber

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateElite') * 16)
        .inputs(ore('wireFineTungstenSteel') * 32)
        .inputs(ore('screwExtreme') * 4)
        .inputs(ore('processorBasic') * 2)
        .fluidInputs(fluid('tungsten_steel') * 1296)
        .outputs(item('qmd:target_chamber_controller'))
        .duration(120).EUt(GTValues.VA[GTValues.HV]).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateElite') * 16)
        .inputs(ore('wireFineTungstenSteel') * 32)
        .inputs(ore('screwRhodiumPlatedPalladium') * 4)
        .inputs(ore('processorElite') * 2)
        .fluidInputs(fluid('iridium') * 16384)
        .outputs(item('qmd:collision_chamber_controller'))
        .duration(120).EUt(GTValues.VA[GTValues.HV]).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateElite') * 16)
        .inputs(ore('wireFineTungstenSteel') * 32)
        .inputs(ore('screwDesh') * 4)
        .inputs(ore('processorBasic') * 2)
        .fluidInputs(fluid('ionized_gold') * 16384)
        .outputs(item('qmd:beam_dump_controller'))
        .duration(120).EUt(GTValues.VA[GTValues.HV]).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('plateElite') * 16)
        .inputs(ore('wireFineTungstenSteel') * 32)
        .inputs(ore('frameGtVoid'))
        .inputs(ore('processorBasic') * 2)
        .fluidInputs(fluid('ionized_gold') * 16384)
        .outputs(item('qmd:decay_chamber_controller'))
        .duration(120).EUt(GTValues.VA[GTValues.HV]).buildAndRegister()