
import gregtech.api.unification.Elements

def Schrabidium = Elements.add(126, 186, -1, null, "Schrabidium", "§bSh§e", false)

def Voidmetal = Elements.add(81, 35, -1, null, "Voidmetal", "§5Vo§e", false)

def Euphemium = Elements.add(-0, -0, -1, null, "Euphemium", "§dEu§e", false)


def Σ = Elements.add(243, 452, -1, null, "Σ", "Σ", false)

def Omegnalium = Elements.add(999, 999, -1, null, "Omegnalium", "Ω", false)

def Adamantium = Elements.add(123, 123, -1, null, "Adamantium", "", false)

def Hiihirokane = Elements.add(242, 124, -1, null, "Hiihirokane", "§cHk", false)

def Manasteel = Elements.add(120, 124, -1, null, "Manasteel", "§9Ml§e", false)

def Terrasteel = Elements.add(245, 124, -1, null, "Terrasteel", "§aTr§e", false)

def Mithglar = Elements.add(40, 256, -1, null, "Mithglar", "§6Mᛁ§7", false)
def Skadiite = Elements.add(45, 128, -1, null, "Skadiite", "§1Ski§9", false)
def Geldrun = Elements.add(50, 512, -1, null, "Geldrun", "§eGn§6", false)
def Vidium = Elements.add(35, 128, -1, null, "Vidium", "§2Vid§a", false)
def Freyrite = Elements.add(48, 64, -1, null, "Freyrite", "§4Fy§c", false)
def Swartim = Elements.add(60, 128, -1, null, "Swartim", "§8Sw§7", false) // Removed Norse characters here
def Trimla = Elements.add(42, 256, -1, null, "Trimla", "§7Tᚱ§f", false)
def Rodanil = Elements.add(55, 512, -1, null, "Rodanil", "§8Rᛟ§6", false)
def Drustins = Elements.add(38, 64, -1, null, "Drustins", "§2Dᚱ§a", false)
def Dowmandir = Elements.add(53, 128, -1, null, "Dowmandir", "§7ᛞo§6", false)
def Breytir = Elements.add(47, 256, -1, null, "Breytir", "§3Bᚱ§b", false)
def Geadris = Elements.add(52, 512, -1, null, "Geadris", "§dGᛖ§5", false)

def Licium = Elements.add(52, 123, -1, null, "Licium", "Lc", false)
def Cerulean = Elements.add(125, 156, -1, null, "Cerulean", "§bCn§f", false)
def Aurorian = Elements.add(256, 156, -1, null, "Aurorian", "§dAo§f", false)
def Assimilation = Elements.add(1, 1, -1, null, "Assimilation", "§4Sim§f", false)

def Aer = Elements.add(10, 14, -1, null, "Aer", "§e✶Ae§e", false)
def Ignis = Elements.add(12, 12, -1, null, "Ignis", "§c✶Ig§e", false)
def Terra = Elements.add(14, 20, -1, null, "Terra", "§2✶Te§e", false)
def Aqua = Elements.add(8, 10, -1, null, "Aqua", "§3✶Aq§e", false)
def Ordo = Elements.add(20, 20, -1, null, "Ordo", "§7✶Or§e", false)
def Perditio = Elements.add(1, 1, -1, null, "Perditio", "§8✶Pd§e", false)
def Vacuos = Elements.add(1, 0, -1, null, "Vacuos", "§7◌Va§e", false)
def Lux = Elements.add(1, 1, -1, null, "Lux", "§f✴Lu§e", false)
def Motus = Elements.add(6, 6, -1, null, "Motus", "§9➤Mo§e", false)
def Gelum = Elements.add(10, 12, -1, null, "Gelum", "§b✳Ge§e", false)
def Vitreus = Elements.add(14, 16, -1, null, "Vitreus", "§b◇Vi§e", false)
def Metallum = Elements.add(26, 30, -1, null, "Metallum", "§7⊠Me§e", false)
def Victus = Elements.add(12, 10, -1, null, "Victus", "§c♥Vi§e", false)
def Mortuus = Elements.add(13, 13, -1, null, "Mortuus", "§4☠Mt§e", false)
def Potentia = Elements.add(15, 15, -1, null, "Potentia", "§d‡Po§e", false)
def Permutatio = Elements.add(1, 17, -1, null, "Permutatio", "§a⇄Pe§e", false)
def Praecantatio = Elements.add(18, 22, -1, null, "Praecantatio", "§5✡Pr§e", false)
def Auram = Elements.add(16, 24, -1, null, "Auram", "§d✦Au§e", false)
def Alkimia = Elements.add(14, 21, -1, null, "Alkimia", "§3◈Ak§e", false)
def Vitium = Elements.add(18, 18, -1, null, "Vitium", "§5☣Vt§e", false)
def Tenebrae = Elements.add(2, 3, -1, null, "Tenebrae", "§0☽Tn§e", false)
def Alienis = Elements.add(22, 28, -1, null, "Alienis", "§5☄Al§e", false)
def Volatus = Elements.add(10, 10, -1, null, "Volatus", "§f⟰Vo§e", false)
def Herba = Elements.add(13, 17, -1, null, "Herba", "§2✿He§e", false)
def Instrumentum = Elements.add(25, 28, -1, null, "Instrumentum", "§9⚒In§e", false)
def Fabrico = Elements.add(26, 29, -1, null, "Fabrico", "§b⚙Fa§e", false)
def Machina = Elements.add(30, 32, -1, null, "Machina", "§1⌬Mc§e", false)
def Vinculum = Elements.add(19, 22, -1, null, "Vinculum", "§8⛓Vn§e", false)
def Spiritus = Elements.add(16, 18, -1, null, "Spiritus", "§7†Sp§e", false)
def Cognitio = Elements.add(20, 20, -1, null, "Cognitio", "§6☼Cg§e", false)
def Sensus = Elements.add(21, 21, -1, null, "Sensus", "§a○Ss§e", false)
def Aversio = Elements.add(22, 22, -1, null, "Aversio", "§4↯Av§e", false)
def Praemunio = Elements.add(23, 23, -1, null, "Praemunio", "§3⛨Pm§e", false)
def Desiderium = Elements.add(24, 24, -1, null, "Desiderium", "§e✪Ds§e", false)
def Exanimis = Elements.add(2, 25, -1, null, "Exanimis", "§7⚱Ex§e", false)
def Bestia = Elements.add(3, 14, -1, null, "Bestia", "§6♘Bs§e", false)
def Humanus = Elements.add(26, 26, -1, null, "Humanus", "§f☺Hu§e", false)
def Sol = Elements.add(20, 10, -1, null, "Sol", "§e☀So§e", false)
def Luna = Elements.add(14, 18, -1, null, "Luna", "§7☾Lu§e", false)
def Stellae = Elements.add( 30, 30, -1, null, "Stellae", "§9✶St§e", false)
def Diabolus = Elements.add(33, 33, -1, null, "Diabolus", "§4⛧Db§e", false)
def Fluctus = Elements.add(10, 16, -1, null, "Fluctus", "§3≈Fl§e", false)
def Sonus = Elements.add(15, 13, -1, null, "Sonus", "§6♪Sn§e", false)
def Exitium = Elements.add( 18, 18, -1, null, "Exitium", "§1☄Ex§e", false)
def Caeles = Elements.add( 28, 28, -1, null, "Caeles", "§e✵Cl§e", false)
def Draco = Elements.add(32, 34, -1, null, "Draco", "§b♛Dr§e", false)
def Infernum = Elements.add(35, 35, -1, null, "Infernum", "§4☢If§e", false)
def Ventus = Elements.add(12, 12, -1, null, "Ventus", "§f〰Vt§e", false)
def Visum = Elements.add(20, 18, -1, null, "Visum", "§a◍Vm§e", false)
def Imperium = Elements.add(34, 34, -1, null, "Imperium", "§6⚑Ip§e", false)
