recipemap('assembler').recipeBuilder()
        .inputs(item('gregtech:meta_item_1', 517))
        .inputs(ore('boltMenrilSteel') * 2)
        .fluidInputs(fluid('electrotine_alloy') * 18)
        .inputs(ore('wireGtSingleCopper') * 3)
        .inputs(ore('curvedPlateSteel') * 1)
        .outputs(item('gregtech:meta_item_1', 516) * 6)
        .duration(160).EUt(7).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(item('gregtech:meta_item_1', 517))
        .inputs(ore('boltMenrilSteel') * 2)
        .fluidInputs(fluid('red_alloy') * 18)
        .inputs(ore('electrotine_alloy') * 3)
        .inputs(ore('wireGtSingleCopper') * 3)
        .inputs(ore('curvedPlateSteel') * 1)
        .outputs(item('gregtech:meta_item_1', 516) * 12)
        .duration(160).EUt(7).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(item('gregtech:meta_item_1', 517))
        .inputs(ore('boltMenrilSteel') * 2)
        .fluidInputs(fluid('electrotine_alloy') * 18)
        .inputs(ore('wireGtSingleCopper') * 3)
        .inputs(ore('curvedPlateSteel') * 1)
        .outputs(item('gregtech:meta_item_1', 516) * 12)
        .duration(160).EUt(7).buildAndRegister()