recipemap('paper_milling').recipeBuilder()
        .inputs(ore('dustWood') * 1)
        .fluidInputs(fluid('water') * 100)
        .outputs(metaitem('dustPaper') * 4)
        .fluidOutputs(fluid('lignin_slurry') * 100)
        .duration(120).EUt(2).buildAndRegister()

recipemap('paper_milling').recipeBuilder()
        .inputs(ore('dustPaper') * 4)
        .fluidInputs(fluid('water') * 100)
        .fluidOutputs(fluid('lignin_slurry') * 100)
        .outputs(item('minecraft:paper') * 4)
        .duration(120).EUt(2).buildAndRegister()

recipemap('roaster').recipeBuilder()
        .inputs(ore('dustWood') * 1)
        .fluidInputs(fluid('lignin_slurry') * 200)
        .outputs(metaitem('dustWood') * 2)
        .fluidOutputs(fluid('water') * 200)
        .duration(240).EUt(2).buildAndRegister()
