recipemap('roaster').recipeBuilder()
        .inputs(ore('crushedSphalerite') * 1)
        .outputs(metaitem('dustSphalerite') * 1)
        .outputs(metaitem('dustCadmium') * 2)
        .outputs(metaitem('dustSulfur') * 2)
        .outputs(metaitem('dustStone') * 2)
        .fluidOutputs(fluid('zinc_vapor') * 488 )
        .duration(400).EUt(32).buildAndRegister()

recipemap('roaster').recipeBuilder()
        .inputs(ore('crushedSulfur') * 1)
        .outputs(metaitem('dustSulfur') * 1)
        .outputs(metaitem('dustPhosphorus') * 2)
        .outputs(metaitem('dustRedPhosphorus') * 2)
        .outputs(metaitem('dustStone') * 2)
        .duration(400).EUt(32).buildAndRegister()

recipemap('roaster').recipeBuilder()
        .inputs(ore('crushedCertusQuartz') * 1)
        .outputs(metaitem('dustCertusQuartz') * 1)
        .outputs(metaitem('dustQuartzite') * 2)
        .outputs(metaitem('dustNetherQuartz') * 2)
        .outputs(metaitem('dustStone') * 2)
        .duration(400).EUt(32).buildAndRegister()

recipemap('roaster').recipeBuilder()
        .inputs(ore('crushedMica') * 1)
        .outputs(metaitem('dustCertusQuartz') * 1)
        .outputs(metaitem('dustQuartzite') * 2)
        .outputs(metaitem('dustNetherQuartz') * 2)
        .outputs(metaitem('dustStone') * 2)
        .duration(400).EUt(32).buildAndRegister()

recipemap('roaster').recipeBuilder()
        .inputs(ore('crushedCoal') * 1)
        .outputs(metaitem('dustCoal') * 2)
        .outputs(metaitem('dustCoke') * 1)
        .outputs(metaitem('dustStone') * 2)
        .outputs(metaitem('dustPureCarbon'))
        .duration(600).EUt(32).buildAndRegister()

recipemap('roaster').recipeBuilder()
        .inputs(ore('blockCharcoal') * 1)
        .outputs(metaitem('dustCharcoal') * 8)
        .outputs(metaitem('dustPureCarbon') * 1)
        .fluidOutputs(fluid('wood_varnish') * 100)
        .duration(600).EUt(32).buildAndRegister()

