recipemap('assembler').recipeBuilder()
        .inputs(ore('foilAluminium') * 4)
        .inputs(ore('wireFineCopper'))
        .fluidInputs(fluid('rubber') * 144)
        .outputs(item('hbm:circuit', 1))
        .duration(60).EUt(8).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('foilAluminium') * 4)
        .inputs(ore('wireFineAnnealedCopper'))
        .fluidInputs(fluid('rubber') * 144)
        .outputs(item('hbm:circuit', 1) * 2)
        .duration(60).EUt(8).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('foilTantalum') * 4)
        .inputs(ore('wireFineAnnealedCopper'))
        .fluidInputs(fluid('rubber') * 144)
        .outputs(item('hbm:circuit', 2) * 2)
        .duration(60).EUt(8).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(ore('foilTantalum') * 4)
        .inputs(ore('wireFineAnnealedCopper'))
        .fluidInputs(fluid('rubber') * 144)
        .outputs(item('hbm:circuit', 2))
        .duration(60).EUt(8).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(item('gregtech:meta_item_1', 402))
        .inputs(ore('wireFineCopper') * 4)
        .inputs(ore('wireGtSingleGold') * 2)
        .fluidInputs(fluid('soldering_alloy') * 144)
        .outputs(item('hbm:circuit', 3))
        .duration(60).EUt(8).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(item('gregtech:meta_item_1', 402))
        .inputs(ore('wireFineAnnealedCopper') * 4)
        .inputs(ore('wireGtSingleGold') * 2)
        .fluidInputs(fluid('soldering_alloy') * 144)
        .outputs(item('hbm:circuit', 3) * 2)
        .duration(60).EUt(8).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(item('gregtech:meta_item_1', 402))
        .inputs(ore('wireFineCopper') * 4)
        .inputs(ore('wireFineIonizedGold') * 2)
        .fluidInputs(fluid('soldering_alloy') * 144)
        .outputs(item('hbm:circuit', 3) * 4)
        .duration(60).EUt(8).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(item('gregtech:meta_item_1', 402))
        .inputs(ore('wireFineAnnealedCopper') * 4)
        .inputs(ore('wireFineIonizedGold') * 2)
        .fluidInputs(fluid('soldering_alloy') * 144)
        .outputs(item('hbm:circuit', 3) * 8)
        .duration(60).EUt(8).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(item('hbm:circuit', 3))
        .inputs(ore('foilGold') * 4)
        .inputs(ore('wireFineAluminium') * 2)
        .fluidInputs(fluid('plastic') * 144)
        .outputs(item('hbm:circuit', 5))
        .duration(60).EUt(8).buildAndRegister()

recipemap('assembler').recipeBuilder()
        .inputs(item('hbm:circuit'))
        .inputs(ore('wireFineAluminium') * 2)
        .fluidInputs(fluid('glass') * 144)
        .outputs(item('hbm:crt_display'))
        .duration(60).EUt(8).buildAndRegister()
