#Splash screen properties
#Fri Oct 17 16:11:57 IST 2025
background=0x000000
memoryGood=0x1AFF80
font=0x00EE00
barBackground=0x002F00
barBorder=0x005F00
memoryLow=0xFFB642
rotate=false
memoryWarn=0xFFB642
showMemory=true
bar=0x1AFF80
enabled=true
resourcePackPath=resources
logoOffset=0
forgeTexture=fml\:textures/gui/forge.png
fontTexture=textures/font/ascii.png
